### ISSUE TITLE
putting books at the center of the interaction?

### ISSUE THREAD

**Issue by rscmbbng** [mouse-reeve/fedireads#54]
Hey! Thanks for you work, really awesome to see it federate already at this early stage!

As I was trying it out, a thought occurred to me of how a different interaction model would fit much better with the federated nature of fedireads. Currently the reviewers and their reviews+comments are actors that are followable across the fediverse. Books on the other hand are not, they are rather passive and even only exist through reference. However what if the book (or maybe a shelf) would also be an object that federates across the fediverse? 

In that model one could search for "http://fedireads-test.glitch.me/book/OL18704688W" through another fediverse client and comment it, review it, share it, without even needing a fedireads account.  Book objects could then have a history of reviews (both from fedireads and from other federated platforms), weighted ratings, and other metadata as part of the 'profile' of the book. 

It is then up to the community behind a particular fedireads instance (let's say specialized in 70s sci-fi) to moderate the comments on that particular book, making sure they are relevant for their context. Or maybe attributing more weight to a particular review because it is very insightful.  

Furthermore, a link could be made between the book profile hosted by community A and the book profile hosted by community B that indicates one is talking about the same book. That way you could have a way of indicating across the fediverse that different communities are talking about the same book, but that '70s sci-fi community' will have a different set of takes on that same book than 'science and technology academic study circle community'

Hope this train of thought is helpful!

**Comment by rscmbbng** [comment]
In response to the README's thoughts and considerations: 

Who gets to define what a book is and who the authors are could also be left to particular communities then. Relying on existing catalogues reaffirms certain norms around what a book is, what publishing is and what authorship is that would exclude for example DIY zines, fanfic, or even proper bound books from places that haven't had the resources to index, collect and submit to canonical collections.  

It could be helpful to have access to canonical databases to import (metadata for) certain works but it would become really a dynamic environment when communities can start adding publications that only they have knowledge of. Putting the book central as the object that federates will allow other communities to discover those non-canonical works as well!

**Comment by mouse-reeve** [comment]
Yeah, I really like this way of looking at it! Thank you. It wouldn't be hard to expose books as ActivityPub objects, which would get us a step closer. 

I think there are two different usage models at play here (correct me if I'm misinterpreting!):

A) a community focuses on specialized material (like zines that aren't commercially published or books that aren't widely read) that they curate specialized content about and/or create themselves, and others outside the community would be interested in their specific copy of that data

B) a community focuses on common materials (like recent hugo award winning science fiction or widely published books) that add reviews to a wide pool of people engaging with that content. They care more about the reviews and data within their own community, but also want to engage with people on other similar instances who are interacting with the same books.

For group A, it would be beneficial to propagate their specific local version of a book, and for group B, it would be beneficial to rely on a shared, "universal" book identifier. Group A would be unhappy with having their book metadata overwritten by an external source like open library, and group B would benefit from getting updated metadata. 

I think the solution might be to have an arbitrary number of book identifiers associated with each copy of a book. So it would default to having OpenLibrary as a canonical identifier, but you could decide as an instance to use something like LoC, wikidata, or an instance-specific uuid instead or in addition. And instances would need to be able to disable canonicalization from openlibrary. 

So, by default you would have books like the exist currently (non-canonical copies of openlibrary data), but you could use other data sources and de-couple books from their original data source and treat your local copy as canonical.

Matching books between instances would be more challenging (but I think, doable enough), as well as displaying differences between a matched book that has different metadata on different instances.

The database entry for books would also need to be expanded to store more specific book data, instead of what it does now which is just copy openlibrary json blobs. 

I don't know what kind of activitypub object makes the most sense for a book if you want to be able to interact with it on many different federated platforms. I think if it was an actor, you wouldn't be able to comment on it in Mastodon. If it was a text status, you couldn't comment on it in pizelfed (I think). It may be that you'd want to tailor how it is sent based on the recipient application, or it may be that there's a better way to do this that I haven't thought of.

Does that all fit in with what you envision? Thanks for reading my extremely long initial thoughts :)

**Comment by mouse-reeve** [comment]
I got a suggestion on mastodon to use library linked data to implement this, consider this a note to self to investigate it further.
https://www.loc.gov/librarians/standards
https://id.loc.gov/
https://www.w3.org/2005/Incubator/lld/
