### ISSUE TITLE
Idea: Replace reviews with tags

### ISSUE THREAD

**Issue by InspectorCaracal** [mouse-reeve/fedireads#55]
(Prompted by a post remarking on the last line in the docs re: "why do we need to use a 5-star+text review system?")

What if, instead of ranking books according to a rating ladder and adding an optional blog-like text post explaining your thoughts, the entire "review" structure is done away with and replaced with tags? Then, instead of averaging all the ladder ratings for a single multi-star review, the book entry can display a tag cloud of the most common X tags added to the book.

This has several advantages, including:

- it's easier to tell what the subjective intent of a tag is than a number of stars
- a tag cloud can convey more information than just "is it good", such as genre, themes
- the idea of a "tag" is implied to be searchable metadata, allowing you to effectively search for books by their "reviews"
- tags are already a commonly used and understood system, meaning the potential problem of a learning curve behind making a new kind of review system is avoided

**Comment by mouse-reeve** [comment]
I really like this idea! The more I think about it the more I like it.

The question that remains for me is, given that these rating systems could co-exist, should we have ladder ratings at all? As a goodreads user, I do think they have utility for me, especially when I'm picking books to read from a list (for example, I used this list for recommendations with rating as a way to narrow it down: https://www.goodreads.com/list/show/126482.Novels_by_Trans_Authors_with_Trans_Protagonists#17313660)

But I'm not sure if that's a sign that ratings are useful, or just that they are the only thing available to me.

**Comment by mouse-reeve** [comment]
activitystreams vocab for tagging: https://www.w3.org/TR/activitystreams-vocabulary/#dfn-tag
I think I can implement this pretty easily next time I have free time.

**Comment by mouse-reeve** [comment]
Okay, I added tagging. The UI around it is kinda confusing, and it still needs tag pages, weight, filtering between local and federated

**Comment by nd-rw** [comment]
I also think it would be cool to do away with the antiquated 5-star review system; this will upset portion of people who insist on having everything ranked and quantified.. but books (..art and people's experiences with them) are a lot more complex than a rating of 1-5. Giving people less options to score something usually makes them think harder about the score they give something also.

I think ranking books by a combination score of something like:
`[number of people who read the book]` **+** `[number of people who recommended the book]`
With the "scoring" options being:
-  _recommend (+1)_
-  _wouldn't-recommend (-1)_
- `null`(0).

Every decently popular book on Goodreads ends up with a meaningless score of 3.57 so a more considered alternative system would be nice imo, but up to you @mouse-reeve !

**Comment by jgamble** [comment]
The review (a.k.a. book discussion) is the whole reason to have an online book service; otherwise you may as well just use Twitter with a link to Worldcat. I like being able to, say, list the stories in a collection and discuss their individual merits, and I like the occasional discussion with other readers that results.

Dumping the star system is fine, but the replacement you suggest is merely going to highlight that popular books will be noted as popular. There may be a better way, but I don't believe that a system that can't be gamed exists.

**Comment by InspectorCaracal** [comment]
@jgamble
Supporting keeping the book blog functionality aside (as I don't have a horse in that race, so to speak), I don't understand how a freeform tagging system would necessarily degrade to a popularity contest. Could you elaborate on your thoughts there?

**Comment by jgamble** [comment]
Most people who read the book will recommend it, since very few people will bother with a book they don't like unless they genuinely believe in reviewing (or just like to hate-read). The end result will be the equivalent of the "meaningless score of 3.57".

All you'll have is another gamed algorithm.

**Comment by nd-rw** [comment]
FYI @jgamble I wasn't suggesting to remove reviews, just the 0-5 scoring system with something else. I also agree that a review score system that can't be gamed doesn't exist - except for having no scoring at all maybe?

**Comment by mouse-reeve** [comment]
I really appreciate all these thoughts!

Another possibility/addition is having targeted recommendations in the form of, for example, "if you liked that book you might like this book"

**Comment by InspectorCaracal** [comment]
@jgamble Ohh I see, you were replying to the comment suggestion that simplifies a 5-star system to a yes/no system, not to my tags. Thank you for explaining!

**Comment by mouse-reeve** [comment]
Thank you all for this conversation! I'm going to close the issue because a) I do think I'm going to keep 5 star ratings (I personally find them useful and I think they're very legible and familiar, which is good), and b) my hope is that by expanding the ways in which you can post about a book, users who don't like that system will be able to prioritize other ways of using the site and interacting.
