### ISSUE TITLE
Approvable Followers

### ISSUE THREAD

**Issue by cthulahoops** [mouse-reeve/fedireads#82]
I'm trying to figure out the best way to follower approval to work, and not sure of the best way to proceed.

At the moment, we have a ManyToMany field followers, which joins through UserRelationship, but really followers should be a subset of this: relationships where status = 'follows'.

Approaches:

1) I want to create a field relationships and properties (follows, requested follow, blocks, etc.) which contain only a subset. This works for the simple case, but properties can't work quite like fields: you can't add to them, they don't work in complex queries (eg ```Q(user__followers=request.user)```). I might just not know Django well enough.

2) Just have the relationships field, and rewrite everything to explicitly check the relationship status everywhere. Going to bug prone. We'll treat a block as a follow eventually.

3) Split the relationships table into separate tables. It's a bit of a pain moving data between them, and harder to express constraints (a user shouldn't follow and request to follow a user at the same time), but will be very straightforward to implement and fast to query.

Leaning towards option 3. Any thoughts?

**Comment by jgamble** [comment]
Thinking in terms of SQL (my default case), I would go with option three. It's not likely (I'm assuming) that you'd deal with more than one relationship at a time. Llist followers, list followed, list blocked can all be handled by single queries, and if you really need to deal with more than one at a time, the SQL join is simple.

My only caveat is that you will need admin-level sanity check queries. Tables will on occasion get out of sync, and checking for that (X is both followed and blocked) is important. One of my biggest beefs with tag-based apps is that they almost always never have a "list the untagged entries" option.

**Comment by mouse-reeve** [comment]
I think I'm on team option 3 as well. I also want to think forward to blocking and muting.

I don't think think there's any reason to have the UserRelationship table at all given this; I created it thinking it would store all kinds of relationships, but as you said, that just creates very complicated tables. I'm thinking it makes sense to have every kind of relationship be a django-created join table (rather than an explicitly defined through table). Does that make sense?

**Comment by jgamble** [comment]
My knowledge of django is zero, I'm afraid. I gave a look through the code and I kinda sorta get the table creation, but I'm afraid I'm only speak in SQL.

But this is a case where "keep the tables really minimal" (third normal form) really shines. Each type of relationship having its own table makes the most sense to me.

**Comment by mouse-reeve** [comment]
oh yes, sorry @jgamble I didn't see your comment when I posted, so I was directing it at @cthulahoops. I think you're right though from a sql perspective! Django automatically creates join tables for many-to-many relationships (which is what I think we should do), and also lets you manually define join tables (which is what I did previously and don't think was the right call). 

And strong agree that it'll take some careful management to maintain sensible relationships.

**Comment by cthulahoops** [comment]
Thank you all! I'll make Option 3 happen.

The through table also stores a creation date and a relationship id. I don't know if we care about those. I don't think the explicit vs implicit through table matters much. I'd tempted to keep them because it let's us store some extra things and provides some more types of queries. Why would you prefer the automatic tables?

+1 to careful maintenance of sensible relationships. (With extra challenges because this is eventually consistent. What are we supposed to do with followers whose node no longer exists?)

**Comment by mouse-reeve** [comment]
yeah you're right, I guess it is sending and receiving relationship IDs in the activitypub objects, better to leave it alone. Thank you!

**Comment by mouse-reeve** [comment]
I just tested following a fedireads user from mastodon and this works! I think the remaining work is:
 - display "follow" buttons for locked users as "request to follow" or whatever
 - send `"manuallyApprovesFollowers": true,` in actor object (I already did this, including it anyway to keep track of my thoughts)
 - mastodon still doesn't recognize accounts as locked on search, idk why
 
But I think those can be separate issues because this works :) Thank you so much!
