### ISSUE TITLE
how to implement the home page activity feed

### ISSUE THREAD

**Issue by mouse-reeve** [mouse-reeve/fedireads#9]
Right now it's just pulling Activity objects from the database, but it's not the right implementation. I'm not confident that I'm storing activities in a good way, for that matter

**Comment by thricedotted** [comment]
I've been attempting to wrap my head around this and leaning pretty hard on your "it should do something smart with inboxes" comment... so here's a thought dump so far. (Also, I'm totally punting on the specifics of the current Activity model for now.)

The spec says that a user's inbox "contains all activities received by the actor", and it should be filterable. It seems fine to assume that the home page feed is derived from this inbox thing. Where do these activities come from? They're either generated locally (I haven't looked into this implementation) or POSTed to the user/shared inbox.

So this leads me to think that every user's inbox is a collection of references to activities -- literally a many-to-many field in the user model? And that gets populated by receiving activities. i.e., if an activity is POSTed to a user's inbox, that activity is... added to their inbox collection. If an activity goes to the shared inbox, then the server checks to see who's following the sender (actor, I guess) and adds it to each of their inbox collections. Home page activity feed is essentially a fancy filtered version of this.

Maybe this was all a really long way of saying "instead of filtering by 'following' at GET time, filter by 'following' at POST time so we've already sorted what to GET". And maybe some of this is a lot more dependent on how Activities are modeled and stored than I've even gotten to thinking about. idk!!
